### ISSUE TITLE
Support authorized calls to S3

### ISSUE THREAD

**Issue by chaws** [Linaro/qa-reports.linaro.org#63]
This is part of a plan to reduce DB responsibilities, in this case to move files away from it to AWS S3.

I was able to make this work with no changes in squad code base. The only trick is to create a `local_settings.py` in pods to point to exact S3 buckets:

```python
# local_settings.py
AWS_S3_REGION_NAME = 'us-east-1'
AWS_STORAGE_BUCKET_NAME = 'staging-qareports-storage' # it'll be one bucket per environment
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
from botocore import UNSIGNED
AWS_S3_SIGNATURE_VERSION = UNSIGNED
```

and then a VPC endpoint will need to be provisioned. This will attach to all private subnets (where pods are running) and will be the associate point between subnet and S3 buckets.

Once VPC-e is created (take note of its id, e.g. vpce-11111), the following policy should be saved to buckets policy:
```json
{
    "Version": "2012-10-17",
    "Id": "Policy1415115909152",
    "Statement": [
        {
            "Sid": "Access-to-specific-VPCE-only",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::staging-qareports-storage",
                "arn:aws:s3:::staging-qareports-storage/*"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:sourceVpce": "vpce-11111"
                }
            }
        }
    ]
}
```

I'll translate VPC-e and bucket creation into terraform files and create a PR with it.

**Comment by mwasilew** [comment]
This is basically the idea. The storage is only defined in settings (local_settings.py in this case). You'll also need to make sure that django-storages and boto3 are installed in containers.

**Comment by chaws** [comment]
Ah yeah, I picked a pod in testing and installed those two, pip3 didn't like it very much :/, it forced installing Django 3! I'll check dependencies later on. Right now, I'm able to list files, read, but it's giving me access denied to write, i'm checking why. Once I figure that out, I think I'll already create buckets and allow production/staging to access S3 by creating local_settings.py

**Comment by mwasilew** [comment]
Hmm, this worked for me:
https://github.com/mwasilew/squad/blob/tests_file_storage/Dockerfile#L58
Maybe there is a new version that forces django3?

**Comment by chaws** [comment]
The error shows up when you try to install `django-storages` with dependencies, just like you did for boto3

**Comment by mwasilew** [comment]
Ah, then install it without deps. IIRC all deps are already there when you install squad.

**Comment by chaws** [comment]
Hum, not really: https://github.com/jschneier/django-storages/blob/master/setup.cfg#L32

It requires Django > 2.2, which squad already supports. We will just need to stop using `python3-django` (which is 1.11) and install Django2 via pip

**Comment by chaws** [comment]
OK, S3 works with the following:

```python
# local_settings.py
AWS_S3_REGION_NAME = 'us-east-1'
AWS_STORAGE_BUCKET_NAME = 'testing-s3-permissions' # it'll be one bucket per environment
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```
each environment (testing/staging/production) will need to have a role with the following policies (each role allows access to its respective s3 bucket):
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::testing-s3-permissions",
                "arn:aws:s3:::testing-s3-permissions/*"
            ]
        }
    ]
}
```
Then, attach this role into a k8s RBAC role to be mapped to pods from EKS (using aws-auth-cm): https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

**Comment by chaws** [comment]
Closed in https://github.com/Linaro/qa-reports.linaro.org/pull/64
